In [237]:
import matplotlib.pyplot as plt
import os
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [155]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
# import matplotlib.pyplot as plt
# import numpy as np
from torchvision.datasets import ImageFolder
# import os
from torchvision import models, transforms
import torch.optim as optim

C:\Users\seann\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\detection\anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:77.)
  device: torch.device = torch.device("cpu"),


In [160]:
import skimage

In [ ]:
# make list of offshore images and inshore images
# make label list for test images 
    # if ... in offshore then 1 else 0
# read in test images

In [29]:
# os.path.abspath(r'sat_img\data\test\images\14_1_1.jpg')
plt.imread(r'C:\Users\seann\dsc_180a\sat_img\data\test\images\14_1_1.jpg')

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [19, 19, 19],
        [20, 20, 20],
        [28, 28, 28]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [15, 15, 15],
        [21, 21, 21],
        [33, 33, 33]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [11, 11, 11],
        [20, 20, 20],
        [31, 31, 31]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [13, 13, 13],
        [23, 23, 23],
        [21, 21, 21]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [22, 22, 22],
        [33, 33, 33],
        [31, 31, 31]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [21, 21, 21],
        [26, 26, 26],
        [21, 21, 21]]], dtype=uint8)

In [50]:
# read in offshore lists and inshore list 
with open(r'C:\Users\seann\dsc_180a\sat_img\data\main\test_offshore.txt') as f:
    off_shore = f.readlines()
    for i in range(len(off_shore)):
        off_shore[i] = off_shore[i].replace('\n','')

with open(r'C:\Users\seann\dsc_180a\sat_img\data\main\test_inshore.txt') as f:
    in_shore = f.readlines()
    for i in range(len(in_shore)):
        in_shore[i] = in_shore[i].replace('\n','')
in_shore

['11_10_27',
 '11_10_28',
 '11_10_29',
 '11_10_30',
 '11_11_27',
 '11_11_28',
 '11_11_29',
 '11_11_30',
 '11_12_27',
 '11_12_28',
 '11_12_29',
 '11_12_30',
 '11_13_28',
 '11_13_29',
 '11_13_30',
 '11_14_29',
 '11_14_30',
 '11_15_30',
 '11_16_25',
 '11_16_29',
 '11_16_30',
 '11_17_25',
 '11_17_26',
 '11_17_28',
 '11_17_29',
 '11_17_30',
 '11_18_28',
 '11_18_29',
 '11_18_30',
 '11_19_24',
 '11_19_25',
 '11_19_28',
 '11_19_29',
 '11_19_30',
 '11_1_10',
 '11_1_11',
 '11_1_12',
 '11_1_13',
 '11_1_14',
 '11_1_15',
 '11_1_16',
 '11_1_5',
 '11_1_6',
 '11_1_7',
 '11_1_8',
 '11_1_9',
 '11_20_18',
 '11_20_24',
 '11_20_27',
 '11_20_28',
 '11_20_29',
 '11_20_30',
 '11_2_10',
 '11_2_11',
 '11_2_12',
 '11_2_13',
 '11_2_14',
 '11_2_15',
 '11_2_5',
 '11_2_6',
 '11_2_7',
 '11_2_8',
 '11_2_9',
 '11_3_10',
 '11_3_11',
 '11_3_12',
 '11_3_13',
 '11_3_7',
 '11_3_8',
 '11_3_9',
 '11_4_10',
 '11_4_8',
 '11_4_9',
 '11_8_2',
 '11_8_29',
 '11_8_30',
 '11_9_29',
 '11_9_30',
 '12_10_27',
 '12_10_28',
 '12_10_29',
 

In [61]:
test_ = []
# off_shore = []
# in_shore = []
test_labels = [] # 1 == offshore, 0 == on_shore
test_fname = []

# with open(r'C:\Users\seann\dsc_180a\sat_img\data\main\test_offshore.txt') as f:
#     while True:
#         line = f.readline()
#         line = line.replace("\n","")
#         filename = line + ".jpg"
#         off_shore.append(filename)
# with open(r'C:\Users\seann\dsc_180a\sat_img\data\main\test_inshore.txt') as f:
#     while True:
#         line = f.readline()
#         line = line.replace("\n","")
#         filename = line + ".jpg"
#         in_shore.append(filename)
        

with open(r'C:\Users\seann\dsc_180a\sat_img\data\main\test.txt') as f:
    test = f.readlines()
    for i in range(len(test)):
        curr_img = test[i].replace('\n','') # get curr img name
        test_fname.append(curr_img)
        if curr_img in off_shore:
            test_labels.append(1)
        else:
            test_labels.append(0)
        test[i] = plt.imread(r'C:\Users\seann\dsc_180a\sat_img\data\test\images\{}.jpg'.format(curr_img))
        

In [100]:
idx = 593
print(test[idx].mean())
print(np.median(test[idx]))
print(test[idx].max())
print(test[idx].min())
print(test_labels[idx])

135.1072578125
135.0
255
0
0


In [146]:
# test[0]
test_gray = []
for img in test:
    test_gray.append(np.dot(img[...,:3], [0.299, 0.587, 0.114]))

In [238]:
X_train, X_test, y_train, y_test = train_test_split(test, test_labels, test_size=0.3)

In [196]:
model = KNeighborsClassifier(2)
model.fit(np.reshape(test_gray[:200],(200,640000)),test_labels[:200])

KNeighborsClassifier(n_neighbors=2)

In [232]:
model.predict(np.reshape(test_gray[557],(1,640000)))

array([1])

In [233]:
test_labels[557]

1

In [231]:
test_fname.index('11_8_25')

557

In [223]:
np.reshape(test[:200],(200,1920000))

array([[  0,   0,   0, ...,  81,  81,  81],
       [ 94,  94,  94, ..., 155, 155, 155],
       [ 45,  45,  45, ...,  90,  90,  90],
       ...,
       [ 94,  94,  94, ..., 142, 142, 142],
       [ 97,  97,  97, ..., 132, 132, 132],
       [100, 100, 100, ..., 126, 126, 126]], dtype=uint8)

In [242]:
model_2 = KNeighborsClassifier(2)
model_2.fit(np.reshape(X_train,(2100,1920000)), y_train)

KNeighborsClassifier(n_neighbors=2)

In [249]:
model_2.score(np.reshape(X_test[:100],(100,1920000)),y_test[:100])

MemoryError: Unable to allocate 1.43 GiB for an array with shape (100, 1920000) and data type float64